name: Tests and Linters

on: [push]

jobs:
  test_py37:
    name: Test python 3.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: | 
          tox -e py37
  test_py27:
    name: Test python 2.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          tox -e py27
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt        
      - name: Lint with flake8
        run: |
          tox -e flake8
      - name: Lint with pylint
        run: |
          tox -e pylint
      - name: Lint with bandit
        run: |
          tox -e bandit
   
    
